# Generated by Django 4.1 on 2022-10-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basiclayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_option',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
