# Generated by Django 4.1 on 2022-10-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basiclayer', '0002_profile_selected_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='selected_option',
        ),
    ]
