# Generated by Django 4.1 on 2022-10-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='no_of_choice',
            new_name='no_of_choices',
        ),
    ]
